// The local `hand-landmarker` module pulls MediaPipeTasksCommon, whose prebuilt
// static framework VENDORS its own copy of GTMSessionFetcher (GTMSessionFetcher.o,
// GTMSessionFetcherService.o, GTMSessionUploadFetcher.o, GTMSessionFetcherLogging.o).
// @react-native-firebase also pulls the GTMSessionFetcher pod, and expo-build-
// properties forces `use_frameworks! :linkage => :static` (required by RNFirebase).
// Both copies then link into the app → ~240 "duplicate symbol" errors. Xcode 16+
// removed the classic linker, so the old `-ld_classic` escape hatch is gone.
//
// Fix: delete the vendored GTMSessionFetcher objects from MediaPipe's static
// archives. MediaPipe declares it needs GTMSessionFetcher/Core >=3.4 <6.0, and the
// Firebase pod ships 5.3.0 (in range), so MediaPipe links cleanly against the pod's
// single copy. We DON'T touch stb_image (ExpoGL collision) — those stay warnings the
// linker dedups on its own, and rewiring MediaPipe's image decode is riskier.
//
// Implemented as a Podfile post_install step (Pods exist only after `pod install`),
// which shells out to a small Python helper. Python is used instead of inline Ruby
// because the surgery is fiddly: the binaries are FAT archives (arm64+x86_64) that
// must be thinned/recombined with lipo, and a member name can appear more than once
// (macOS `ar d` removes only the first match per call). Expo regenerates ios/ every
// prebuild, so both the helper and the Podfile hook are (re)written here.
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const HELPER = 'mp_dedupe.py';
const MARKER = '# mediapipe-dedupe';

const HELPER_SRC = `#!/usr/bin/env python3
# Auto-generated by plugins/withMediaPipeDedup.js — do not edit by hand.
import os, subprocess, sys, tempfile

DUP = {"GTMSessionFetcher.o", "GTMSessionFetcherService.o",
       "GTMSessionUploadFetcher.o", "GTMSessionFetcherLogging.o"}

def run(args):
    return subprocess.run(args, capture_output=True, text=True)

def is_ar(path):
    return "ar archive" in run(["file", "-b", path]).stdout

def members(a):
    return run(["ar", "t", a]).stdout.splitlines()

def strip_thin(a):
    while True:
        hit = next((m for m in members(a) if m in DUP), None)
        if hit is None:
            break
        if run(["ar", "d", a, hit]).returncode != 0:
            break
    run(["ranlib", a])

def process(bin_path):
    if not is_ar(bin_path):
        return
    archs = run(["lipo", "-archs", bin_path]).stdout.split()
    if len(archs) > 1:
        thins = []
        for arch in archs:
            t = tempfile.mktemp(suffix="." + arch + ".a")
            run(["lipo", bin_path, "-thin", arch, "-output", t])
            strip_thin(t)
            thins.append(t)
        run(["lipo", "-create", *thins, "-output", bin_path])
        for t in thins:
            os.path.exists(t) and os.remove(t)
    else:
        strip_thin(bin_path)

root = sys.argv[1] if len(sys.argv) > 1 else "."
mp = os.path.join(root, "MediaPipeTasksCommon")
if not os.path.isdir(mp):
    print("[mediapipe-dedupe] MediaPipeTasksCommon not found, nothing to do")
    sys.exit(0)
count = 0
for dp, _, fns in os.walk(mp):
    for fn in fns:
        p = os.path.join(dp, fn)
        if is_ar(p):
            process(p)
            count += 1
print("[mediapipe-dedupe] stripped vendored GTMSessionFetcher from %d MediaPipe archive(s)" % count)
`;

module.exports = function withMediaPipeDedup(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const iosRoot = config.modRequest.platformProjectRoot;
      // 1. (Re)write the helper next to the Podfile.
      fs.writeFileSync(path.join(iosRoot, HELPER), HELPER_SRC);

      // 2. Inject a post_install line that runs it against the Pods sandbox.
      const podfile = path.join(iosRoot, 'Podfile');
      let contents = fs.readFileSync(podfile, 'utf8');
      if (!contents.includes(MARKER)) {
        const anchor = '  post_install do |installer|';
        if (!contents.includes(anchor)) {
          throw new Error('withMediaPipeDedup: could not find post_install anchor in Podfile');
        }
        const line =
          `\n    ${MARKER}\n` +
          `    system('/usr/bin/python3', File.join(__dir__, '${HELPER}'), installer.sandbox.root.to_s) ` +
          `|| Pod::UI.warn('[mediapipe-dedupe] helper failed — check for duplicate GTMSessionFetcher symbols')`;
        contents = contents.replace(anchor, `${anchor}${line}`);
        fs.writeFileSync(podfile, contents);
      }
      return config;
    },
  ]);
};
