// Local Expo config plugin: bundles assets/sounds/notification.wav into the
// native projects so notifee (Android) / APNs (iOS) can play it as the push
// sound. android/ and ios/ are generated by `expo prebuild`, so we inject the
// file on every prebuild via dangerous mods rather than committing native dirs.
//
// Android: res/raw/notification.wav → referenced by name "notification" on the
//   notification CHANNEL (see mobile/src/features/notifications/push.js) and in
//   the backend FCM payload (android.notification.sound = "notification").
// iOS: copied next to Info.plist and added to the bundle → referenced as
//   "notification.wav" in the APNs payload. (iOS push is dormant until there's a
//   paid Apple account / APNs, but bundling it now is harmless and future-proof.)

const { withDangerousMod, withXcodeProject } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SOUND_REL = path.join("assets", "sounds", "notification.wav");
const SOUND_FILE = "notification.wav";

function withAndroidSound(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const src = path.join(cfg.modRequest.projectRoot, SOUND_REL);
      const rawDir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res", "raw");
      if (fs.existsSync(src)) {
        fs.mkdirSync(rawDir, { recursive: true });
        fs.copyFileSync(src, path.join(rawDir, SOUND_FILE));
      } else {
        console.warn(`[withNotificationSound] missing ${src} — Android sound not bundled`);
      }
      return cfg;
    },
  ]);
}

function withIosSound(config) {
  // 1. Copy the file into the iOS project folder (next to Info.plist).
  config = withDangerousMod(config, [
    "ios",
    (cfg) => {
      const src = path.join(cfg.modRequest.projectRoot, SOUND_REL);
      const dest = path.join(cfg.modRequest.platformProjectRoot, cfg.modRequest.projectName || "", SOUND_FILE);
      if (fs.existsSync(src)) {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
      }
      return cfg;
    },
  ]);

  // 2. Register it as a bundle resource in the Xcode project.
  config = withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const group = project.findPBXGroupKey({ name: cfg.modRequest.projectName });
    if (group && !project.hasFile(SOUND_FILE)) {
      project.addResourceFile(SOUND_FILE, { target: project.getFirstTarget().uuid }, group);
    }
    return cfg;
  });

  return config;
}

module.exports = function withNotificationSound(config) {
  config = withAndroidSound(config);
  config = withIosSound(config);
  return config;
};
